# Generated by Django 4.2.1 on 2023-05-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Bloodgroup', models.CharField(max_length=50)),
                ('Datejoininng', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('Salarytype', models.CharField(max_length=50)),
                ('Workinghour', models.IntegerField(default=0)),
                ('Overtime', models.IntegerField(default=0)),
                ('Casualleave', models.IntegerField(default=0)),
                ('Basicsalary', models.IntegerField(default=0)),
                ('HRA', models.IntegerField(default=0)),
                ('MedicalAllowance', models.IntegerField(default=0)),
                ('Coveneyance', models.IntegerField(default=0)),
                ('General', models.IntegerField(default=0)),
                ('Professionaltax', models.IntegerField(default=0)),
                ('RD', models.IntegerField(default=0)),
                ('PF', models.IntegerField(default=0)),
                ('ESI', models.IntegerField(default=0)),
                ('leave_count', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('on_leave', models.BooleanField(blank=True, null=True)),
                ('Netsalary', models.IntegerField(default=0)),
                ('Checkin_status', models.BooleanField(blank=True, null=True)),
                ('Check_in', models.DateTimeField(blank=True, help_text='Time in', null=True)),
                ('Check_out', models.DateTimeField(blank=True, help_text='Time out', null=True)),
                ('WorkedHour', models.IntegerField(default=0)),
                ('Date', models.CharField(max_length=50)),
            ],
        ),
    ]
