# Generated by Django 4.2.1 on 2023-05-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMSAPI', '0003_rename_fname_register_login_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register_login',
        ),
    ]
