# Generated by Django 4.2.1 on 2023-06-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSAPI', '0004_delete_register_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='Address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Bloodgroup',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
