# Generated by Django 4.2.1 on 2023-06-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSAPI', '0005_alter_employeedata_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='Bloodgroup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='DOB',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Datejoininng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Salarytype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
