# Generated by Django 4.2.1 on 2023-06-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSAPI', '0006_alter_employeedata_bloodgroup_alter_employeedata_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_entrys_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entry', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField()),
                ('trace_back', models.CharField(blank=True, null=True)),
                ('IP_address', models.CharField(blank=True, null=True)),
                ('path', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
