# Generated by Django 4.2.1 on 2023-06-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMSAPI', '0007_log_entrys_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_role', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employees_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='salary_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employeedata',
            name='employee_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='EMSAPI.employees_type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSAPI.employee_role'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Salarytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSAPI.salary_type'),
        ),
    ]
