# Generated by Django 4.2.1 on 2023-06-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMSAPI', '0008_employee_role_employees_type_salary_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees_type',
            old_name='employee_type',
            new_name='employees_type',
        ),
    ]
