# Generated by Django 4.2.1 on 2023-06-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMSAPI', '0009_rename_employee_type_employees_type_employees_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_of_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplemplrl', to='EMSAPI.employee_role'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='Salarytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplempltyp', to='EMSAPI.salary_type'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='employee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplemplemptp', to='EMSAPI.employees_type'),
        ),
        migrations.CreateModel(
            name='company_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=40, null=True)),
                ('company_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EMSAPI.type_of_company')),
            ],
        ),
        migrations.AddField(
            model_name='employee_role',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EMSAPI.company_name'),
        ),
    ]
