# Generated by Django 4.2.1 on 2023-06-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMSAPI', '0012_employee_skill_employeedata_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_skill',
            name='Employee_skill',
        ),
        migrations.RemoveField(
            model_name='employeedata',
            name='skills',
        ),
        migrations.AddField(
            model_name='employee_skill',
            name='employeeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empskemplo', to='EMSAPI.employeedata'),
        ),
        migrations.AddField(
            model_name='employee_skill',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empskslikk', to='EMSAPI.skill'),
        ),
    ]
