# Generated by Django 4.2.1 on 2023-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSAPI', '0015_alter_employeedata_netsalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='Netsalary',
            field=models.IntegerField(default=0),
        ),
    ]
